openapi: 3.0.1
info:
  title: Kahala Game REST API.
  description: Manage Kahala resources.
  contact:
    email: joerid@gmail.com
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  version: 1.0.0
servers:
- url: http://localhost:8081
tags:
- name: Game
  description: Manage Game resources.
- name: Status
  description: Health check endpoint
paths:
  /game:
    post:
      tags:
      - Game
      summary: Create Game
      description: Create a new game
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /game/{GameId}:
    get:
      tags:
      - Game
      summary: Find Game by Id
      description: Returns a single Game resource
      parameters:
      - name: GameId
        in: path
        description: ID of Game to return.
        required: true
        schema:
          type: string
          format: UUID
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Resource not found
          content: {}
    patch:
      tags:
        - Game
      summary: Patch a Game resource.
      description: Patch a single attribute of a Game resource by Id.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /status:
    get:
      tags:
      - Status
      summary: Health check endpoint
      responses:
        200:
          description: Success
components:
  schemas:
    Game:
      type: object
      properties:
        _id:
          type: string
          format: UUID
          example: 033252ca-f940-483e-8171-6beaf869169f
        playerIdTurn:
          type: integer
        players:
          $ref: '#/components/schemas/Player'
        createdAt: 
          type: string
          format: ISO 8601
        updatedAt: 
          type: string
          format: ISO 8601
    Player:
      type: object
      properties:
        score:
          type: integer
        name:
          type: string
        pits:
          type: array
          example: [6, 6, 6, 6, 6, 6]
    ApiErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
